config/routes.rb
#
# Some of these are not used for routes right now. But we still reserve
# them for later use.
# posts is currently used in routes from the moderation mod.
#
unless defined?(FORBIDDEN_NAMES)
  FORBIDDEN_NAMES = %w[
    account admin none assets avatars chat code debug do groups
    javascripts me networks page pages people pictures places posts
    issues session static stats stylesheets theme wikis
  ].freeze
end

#  See http://guides.rubyonrails.org/v3.1.0/routing.html

Crabgrass::Application.routes.draw do
  ##
  ## CRON JOBS
  ##

  post '/do/cron/run(/:id)', to: 'cron#run', format: false,
                             constraints: { ip: /127.0.0.1/ }

  ##
  ## STATIC FILES AND ASSETS
  ##

  # same as the asset_path without
  resources :assets, only: [:destroy], as: 'destroy_asset'
  get '/assets/:id/versions/:version/*path',
      to: 'assets#show',
      as: 'asset_version'
  get '/assets/:id(/*path)', to: 'assets#show', as: 'asset'

  scope format: false do
    get 'avatars/:id/:size.jpg',
      to: 'avatars#show',
      as: 'avatar',
      constraints: { size: /#{Avatar::SIZES.keys.join('|')}/ }
    get 'theme/:name/*file.css', to: 'theme#show'
  end

  get 'pictures/:id1/:id2(/:geometry)',
      to: 'pictures#show',
      as: 'pictures'

  ##
  ## ME
  ##

  namespace 'me' do
    delete 'notices/destroy_all',
      to: 'notices#destroy_all',
      as: 'notices_destroy_all'
    resources :notices, only: %i[index show destroy]
    get '', to: 'notices#index', as: 'home'
    # resource  :page, only: [:new, :create]
    resources :recent_pages, only: [:index]
    match 'pages(/*path)', to: 'pages#index', as: 'pages', via: %i[get post]
    resources :discussions, path: 'messages', only: :index do
      resources :posts, except: [:new]
    end
    resource  :settings, only: %i[show update]
    resource  :destroy, only: %i[show update]
    resource  :password, only: %i[edit update]
    resources :permissions, only: %i[index update]
    resource  :profile, controller: 'profile', only: %i[edit update]
    resources :requests, only: %i[index update destroy show]
    # resources :events, only: [:index]
    resource :avatar, only: %i[create edit update destroy]
    resources :tasks, only: [:index]
  end

  ##
  ## EMAIL
  ##

  # UPGRADE: this is pre rails 3 syntax. If you want to bring these
  # routes back please upgrade them
  #  match '/invites/:action/*path', controller: 'requests', action: /accept/
  #  match '/code/:id', to: 'codes#jump'

  ##
  ## ACCOUNT
  ##

  resource :account, only: %i[new create]
  match 'account/reset_password(/:token)',
        as: 'reset_password',
        to: 'accounts#reset_password',
        via: %i[get post]

  post 'session/language', as: 'language', to: 'session#language'
  post 'session/login', as: 'login', to: 'session#login'
  post 'session/logout', as: 'logout', to: 'session#logout'
  # ajax login form
  get 'session/login_form', as: 'login_form', to: 'session#login_form',
                            constraints: ->(request) { request.xhr? }

  ##
  ## ENTITIES
  ##

  # autocomplete queries, restricted to ajax
  resources :entities, only: [:index],
                       constraints: ->(request) { request.xhr? }

  ##
  ## PEOPLE
  ##

  match 'people/directory(/*path)',
        as: 'people_directory',
        to: 'person/directory#index',
        via: %i[get post]

  resources :people, module: 'person', controller: 'home', only: :show do
    resource :home, only: :show, controller: 'home'
    match 'pages(/*path)', as: 'pages', to: 'pages#index', via: %i[get post]
    # resources :messages
    resource :friend_request, only: %i[new create destroy]
  end

  ##
  ## GROUP
  ##

  get 'networks/directory(/*path)',
    as: 'networks_directory',
    to: 'group/directory#index'
  get 'groups/directory(/*path)',
    as: 'groups_directory',
    to: 'group/directory#index'

  resources :groups, module: 'group', only: %i[new create destroy] do
    # content related
    resource :home, only: [:show], controller: 'home'
    match 'pages(/*path)', as: 'pages', to: 'pages#index', via: %i[get post]
    resource  :avatar, only: %i[create edit update]
    resources :wikis, only: %i[create index]

    # membership related
    resources :memberships, only: %i[index create destroy]
    resources :my_memberships, only: %i[create destroy]
    resources :membership_requests, except: %i[new edit]
    resource  :invite, only: %i[new create]

    # settings related
    resource  :settings, only: %i[show update]
    resources :requests, except: %i[new edit]
    resources :permissions, only: %i[index update]
    resource  :profile, only: %i[edit update]
    resource  :structure, only: %i[show new create update]
  end

  ##
  ## DEBUGGING
  ##

  if Rails.env.development?
    post 'debug/become', as: 'debug_become', to: 'debug#become'
    get 'debug/break', as: 'debug_break', to: 'debug#break'
  end
  # There's no bugreport controller right now it seems
  # match 'debug/report/submit', as: 'debug_report', to: 'bugreport#submit'

  ##
  ## NORMAL PAGE ROUTES
  ##

  # default page creator
  get '/pages/create(/:owner(/:type))',
      as: 'page_creation',
      to: 'page/create#new'
  post '/pages/create(/:owner(/:type))',
       to: 'page/create#create'

  # base page
  resources :pages, module: 'page', controller: 'base', only: [] do |_pages|
    resources :participations, only: %i[index update create]
    # resources :changes
    resources :assets, only: %i[index update create]
    resources :tags, only: %i[index create destroy show], :constraints => { :id => /.*/ }
    resources :posts, except: [:new]

    # page sidebar/popup controllers:
    resource :sidebar,    only: [:show]
    resource :share,      only: %i[show update],
                          constraints: ->(request) { request.xhr? }
    resource :details,    only: [:show]
    resource :history,    only: [:show], controller: 'history'
    resource :attributes, only: [:update]
    resource :title,      only: %i[edit update], controller: 'title'
    resource :trash,      only: %i[edit update], controller: 'trash'
  end

  resources :posts, only: [] do |_posts|
    resource :star, only: %i[create destroy]
  end

  ##
  ## WIKI
  ##

  resources :wikis, module: 'wiki', only: %i[show edit update] do
    member do
      get 'print'
    end
    resource :lock, only: %i[destroy update]
    resources :assets, only: %i[new create]
    resources :versions, only: %i[index show] do
      member do
        post 'revert'
      end
    end
    resources :diffs, only: [:show]
  end

  ##
  ## OTHER ROUTES
  ##

  root to: 'root#index'
  get '/do/static/greencloth', to: 'static#greencloth'

  ##
  ## SPECIAL PATH ROUTES for PAGES and ENTITIES
  ##

  resources :contexts, path: '', only: :show do
    resources :pages, path: '',
                      controller: :context_pages,
                      only: %i[show edit] do
      member do
        get 'print'
      end
    end
  end

  #
  # I'm not sure we will ever want this...
  # deeply nested routes are considered a bad practice and even though
  # the url does not grow as much this basically boils down to using
  # a deeply nested approach.
  #
  # Instead we probably want
  # /pages/:page_id/...
  #
  # scope path: ':context_id/:page_id/:controller' do
  #  resources :context_page_items, path: '' do
  #    collection do
  #      post :sort
  #    end
  #  end
  # end
end

app/controllers/page/shares_controller.rb
#
# PAGE SHARING
#
#
# Handles the sharing and notification of pages
#
# share this page with a notice message to any number of recipients.
#
# if the recipient is a user name, then the message and the page show up in
# user's inbox, and optionally they are alerted via email.
#
# if the recipient is an email address, an email is sent to the address with a
# magic url that lets the recipient view the page by clicking on a link
# and using their email as the password.
#
# the sending user must have admin access to send to recipients
# who do not already have the ability to view the page.
#
# the recipient may be an entire group, in which case we grant access
# to the group and send emails to each user in the group.
#
# you cannot share to users/groups that you cannot pester, unless
# the page is private and they already have access.
#
class Page::SharesController < Page::SidebarsController
  guard update: :may_share_page?

  helper 'page/share', 'page/participation'

  before_filter :close_popup, only: :update, if: :cancel_update?
  before_filter :add_recipients, only: :update, if: :add_recipients?
  track_actions :update

  # display the share or notify forms.
  # this returns the html, which is used to populate the modalbox
  def show
    render template: "page/shares/show_#{mode_param}"
  end

  # there are two modes:
  #
  #  params[:share]  --> add new access, maybe notify
  #  params[:notify] --> send notice, maybe add access.
  #
  # there are four ways to submit the forms:
  #
  #   (1) cancel button (params[:cancel]==true)
  #       -> before_filter :close_popup
  #   (2) add button or return in add field (params[:add]==true)
  #       -> before_filter :add_recipients
  #   (3) share button (params[:share_button]==true)
  #   (3) notify button (params[:notify_button]==true)
  #
  # recipient(s) examples:
  #
  # * when updating the form:
  #   {"recipient"=>{"name"=>"", "access"=>"admin"}}
  #
  # * when submitting the form:
  #   {"recipients"=>{"aaron"=>{"access"=>"admin"},
  #    "the-true-levellers"=>{"access"=>"admin"}}
  #
  def update
    @success_message = I18n.t(notify_or_share_message)
    notify_or_share
  end

  protected

  #
  # Main Update Task
  #
  def notify_or_share
    if params[:share_button] || params[:notify_button]
      share = Page::Share.new(@page, current_user, share_options)
      @uparts, @gparts = share.with params[:recipients]
      @page.save!
      success(@success_msg)
    end
    close_popup
  rescue ActiveRecord::RecordNotFound
    warning I18n.t('autocomplete.placeholder.enter_name_of_group_or_person')
    refresh_sidebar
  end

  def share_options
    options = params[:notification] || HashWithIndifferentAccess.new
    convert_checkbox_boolean(options)
    options[:send_notice] ||= params[:notify_button].present?
    options.reverse_merge mailer_options: mailer_options
  end

  #
  # Before Filters
  #

  # we allow for an id of 0 for pages just getting created
  def fetch_page
    @page = Page.new if params['page_id'] == '0'
    @page || super
  end

  def cancel_update?
    params[:cancel]
  end

  def add_recipients
    @recipients = build_recipient_array
    render partial: 'page/shares/add_recipient', locals: { alter_access: share? }
  end

  def add_recipients?
    params[:add]
  end

  #
  # After Filters
  #

  def track_action(_event = nil, _options = {})
    @uparts.each do |part|
      if part.previous_changes.keys.include? 'access'
        super('update_user_access', participation: part)
      end
    end
    @gparts.each do |part|
      if part.previous_changes.keys.include? 'access'
        super('update_group_access', participation: part)
      end
    end
  end

  #
  # Handling recipients
  #
  def build_recipient_array
    if params[:recipient] and params[:recipient][:name].present?
      recipients_names = params[:recipient][:name].strip.split(/[, ]/)
      recipients_names.map do |recipient_name|
        find_recipient(recipient_name, mode_param)
      end.compact
    else
      []
    end
  end

  #
  # given a recipient name, we try to find an appriopriate user or group object.
  # a lot can go wrong: the name might not exist, you may not have permission,
  # the user might already have access, etc.
  #
  def find_recipient(recipient_name, action = :share)
    recipient_name.strip!
    return nil unless recipient_name.present?
    recipient = User.find_by_login(recipient_name) || Group.find_by_name(recipient_name)
    if recipient.nil?
      error(:thing_not_found.t(thing: h(recipient_name)))
      return nil
    elsif !current_user.may?(:pester, recipient)
      error(:share_pester_error.t(name: recipient.name))
      return nil
    elsif @page
      upart = recipient.participations.find_by_page_id(@page.id)
      if upart && action == :share && !upart.access.nil?
        notice(:share_already_exists_error.t(name: recipient.name))
        return nil
      elsif upart.nil? && action == :notify
        if !recipient.may?(:view, @page) and !may_share_page?
          error(:notify_no_access_error.t(name: recipient.name))
          return nil
        end
      end
    end
    recipient
  end

  private

  #
  # Utility Methods
  #
  SUCCESS_MESSAGES = { share: :shared_page_success, notify: :notify_success }.freeze

  def notify_or_share_message
    SUCCESS_MESSAGES[mode_param]
  end

  def mode_param
    mode = params[:mode]
    raise ErrorMessage, 'bad mode' unless %w[notify share].include? mode
    mode.to_sym
  end

  def share?
    mode_param == :share
  end

  # convert {:checkbox => '1'} to {:checkbox => true}
  def convert_checkbox_boolean(hsh)
    hsh.each_pair do |key, val|
      if val == '0'
        hsh[key] = false
      elsif val == '1'
        hsh[key] = true
      end
    end
  end
end

app/helpers/page/share_helper.rb
module Page::ShareHelper
  def page_access_options(options = {})
    @access_options ||= [
      [I18n.t(:page_access_admin), 'admin'],
      [I18n.t(:page_access_edit), 'edit'],
      [I18n.t(:page_access_view), 'view']
    ]
    if options[:remove]
      @access_options + [[I18n.t(:page_access_none), 'remove']]
    elsif options[:blank]
      @access_options + [[format('(%s)', I18n.t(:no_change)), '']]
    else
      @access_options
    end
  end

  # displays the access level of a participation.
  # eg:
  #   <span class="admin">Full Access</span>
  #
  def display_access(participation)
    if participation
      access = participation.access_sym.to_s
      if access.empty? and @page
        participation = @page.most_privileged_participation_for(participation.entity)
        access = participation.access_sym.to_s
      end
      option = page_access_options.find { |option| option[1] == access }
      content_tag :span, option[0], class: access if option
    end
  end

  def display_access_icon(participation)
    icon = case participation.access_sym
           when :admin then 'tiny_wrench'
           when :edit then 'tiny_pencil'
           when :view then 'tiny_no_pencil'
    end
    icon_tag(icon)
  end

  #
  # creates a select tag for page access
  #
  # There are two forms:
  #
  #   select_page_access(name, participation, options)
  #   select_page_access(name, options)
  #
  # options:
  #
  #  [blank] if true, include 'no change' as an option
  #  [expand] if true, show as list instead of popup.
  #  [remove] if true, show an entry that allows for access removal
  #
  def select_page_access(name, participation = {}, options = nil)
    if participation.is_a?(Hash)
      options = participation
      selected = options[:selected]
    else
      selected = participation.access_sym
    end

    options = options.reverse_merge(blank: true, expand: false, remove: false, class: 'access')
    select_options = page_access_options(blank: options[:blank], remove: options.delete(:remove))
    selected ||= if options.delete(:blank)
                   ''
                 else
                   Conf.default_page_access
                 end
    options[:size] = select_options.size if options.delete(:expand)
    options[:style] = 'width: auto'
    options[:class] = 'form-control'
    select_tag name, options_for_select(select_options, selected.to_s), options
  end

  protected

  def add_action(recipient, access, spinner_id)
    access ||= may_select_access_participation? ?
      "$('recipient[access]').value" :
      "'#{Conf.default_page_access}'"
    {
      url: { controller: 'base_page/share', action: 'update', page_id: nil, add: true },
      with: %('recipient[name]=#{recipient.name}&recipient[access]=' + #{access}),
      loading: spinner_icon_on('spacer', spinner_id),
      complete: spinner_icon_off('spacer', spinner_id)
    }
  end

  # the remote action that is triggered when the 'add' button is pressed (or
  # the popup item is selected).
  def widget_add_action(action, add_button_id, access_value)
    {
      url: { controller: 'base_page/share', action: action, page_id: @page.id, add: true },
      with: %{'recipient[name]=' + $('recipient_name').value + '&recipient[access]=' + #{access_value}},
      loading: spinner_icon_on('plus', add_button_id),
      complete: spinner_icon_off('plus', add_button_id)
    }
  end

  def add_recipient_widget_key_press_function(add_action)
    eat_enter = 'return(!enterPressed(event));'
    only_on_enter_press = "enterPressed(event) && $('recipient_name').value != ''"
    remote_function(add_action.merge(condition: only_on_enter_press)) + eat_enter
  end
end

app/views/page/shares/_add_recipient_widget.html.haml
-
-  mode = 'share' if mode.nil? # either 'share' or 'notify'
-  add_button_id = 'add_recipient_button'
-  access_value = may_select_access_participation? ? "$('recipient_access').value" : "'#{Conf.default_page_access}'"
-
-  # this is a little hacky: page_share_path is a nested resource of page, which makes sense. there
-  # is one specific case when we don't need a page, however, and that is when we simply want to
-  # add users in the page creation form. to ensure that the route for page_share_path generates, we ensure
-  # that the page has an ID, even if it is a dummy one.
-
-  page = @page || Page.new
-  page.id = 0 if page.id.nil?
-
-  # the remote action that is triggered when the 'add' button is pressed (or
-  # the popup item is selected).
-
-  add_action = {url: page_share_path(page, mode: mode, add: true).html_safe, method: 'put', with: "'recipient[name]=' + $('recipient_name').value + '&recipient[access]=' + #{access_value}", loading: spinner_icon_on('plus', add_button_id), complete: spinner_icon_off('plus', add_button_id)}
-
-  # (1) submit the form when the enter key is pressed in the text box
-  # (2) don't submit the form if the recipient name field is empty
-  # (3) eat the event by returning false on a enter key so that the form
-  #     is not submitted.
-
-  eat_enter = "return(!enterPressed(event));"
-  only_on_enter_press = "enterPressed(event) && $('recipient_name').value != ''"
-  key_pressed_function = remote_function(add_action.merge(condition: only_on_enter_press)) + eat_enter;
-
-  # this is called after an item in the popup has been selected.
-  # it makes it so selecting an item is like hitting the add button
-  # we clear the recipient_name field so that we don't get a double submit
-
-  after_update_function = "function(value, data) { #{remote_function(add_action)}; $('recipient_name').value='';}"

%table.share_page_recipient_add.full_width
  %tr
    %td#autocomplete_container{style:'width:100%'}
      = autocomplete_entity_field_tag 'recipient_name',
        style: 'width:100%',
        onkeypress: key_pressed_function,
        onselect: after_update_function,
        container: 'autocomplete_container',
        placeholder: :enter_name_of_group_or_person
    %td= "&nbsp;".html_safe
    %td
      - if mode == 'share' and may_select_access_participation?
        = select_page_access 'recipient[access]', blank: false
      - else
        = hidden_field_tag 'recipient[access]'
    %td= "&nbsp;".html_safe
    %td= link_to_remote_icon('plus', add_action, id: add_button_id)

#share_page_recipient_area.autocomplete_results_area.p{style: "display:none"}
  = render 'page/shares/list_of_recipients'

app/views/page/shares/_list_of_recipients.html.haml
-# please do not add here a list of current participants: it makes pages with many participants impossibly slow. Also, it creates very complicated and buggy page sharing logic.
%table.styled.full_width
  %tbody.autocomplete_results_table#share_page_recipient_table

app/views/page/shares/_notification_message_form.html.haml
-
- forced_send     = false if forced_send.nil?
- send_notice     = false if send_notice.nil?
- include_message = false if include_message.nil?
- send_email      = false if send_email.nil?
- #include_email_option = (@current_site && @current_site.never_pester_users) ? false : true
- include_email_option = true
- check_box_options = {checked: send_notice, onclick: "checkboxToggle(this, 'notification_details');" + resize_modal}
- if forced_send
  - check_box_options.merge!({checked: true, disabled: true})
  - send_notice = true

.checkbox
  %label
    = check_box :notification, :send_notice, check_box_options
    = :share_send_notification.t

-# don't include the rest at all if sharing emails is disabled
- style = send_notice ? '' : 'display:none'
#notification_details{style: style}
  - if include_email_option
    .checkbox
      %label
        = check_box :notification, :send_email, checked: send_email
        = :send_email.t
    = :share_include_message.t
    #share_message_holder
      = text_area(:notification, :send_message, rows: 6, class: 'form-control')

app/views/page/shares/_notify_form.html.haml
= page_popup_form('notify') do
  .legend= :recipients.t
  = render 'add_recipient_widget', empty_box: true, mode: 'notify'
  - if (@page.contributors_count || 0) > 0
    .checkbox.p
      %label
        = check_box 'recipients', ':contributors'
        = :notify_contribution.t.html_safe
  .checkbox.p
    %label
      = check_box 'recipients', ':participants'
      = :notify_current_access.t.html_safe

  .legend= :notification_message.t
  = render 'notification_message_form', forced_send: true

  .buttons-right
    = spinner 'popup'
    = close_modal_button(:cancel)
    = submit_tag :notify_page_link.t, name: 'notify_button', class: 'btn btn-primary'

app/views/page/shares/_recipient.html.haml
-# locals to take
-
-# recipient -> the recipient to render the partial for
-# access    -> what access level do we want to give to the new participation
-# unsaved   -> flag: does this participation contain changes that need to be saved / is new
-# blank     -> include blank as an access level option.
-# alter_access -> if true, then we allow the user to change the access level of pre-existing participations.
-
- blank = false if blank.nil?
- access = 'admin' if access.nil?
- access_options = {blank: blank, selected: access}
- if unsaved.nil?
  - newitem = false
- else
  - newitem = unsaved
- newitem = true if @page and @page.new_record?
- alter_access = true if alter_access.nil?
- 
- participation = (@page.participation_for(recipient) if @page)
- 
- id = "share_recipient_%s" % recipient.name
- remove_function = "$('%s').remove()" % id
- tr_class = newitem ? 'unsaved' : ''

%tr{class: tr_class, id: id}
  %td{style:"width:100%"}
    = display_entity(recipient, avatar: 'xsmall', format: :both, block: true)
  %td
    - if (!alter_access && participation) || !may_share_page?
      = hidden_field_tag "recipients[#{recipient.name}]", "1", id: id
      = display_access(participation)
    - elsif may_select_access_participation?
      = select_page_access "recipients[#{recipient.name}][access]", access_options
    - else
      -# why is this included as a hidden field if you are not allowed to set the access level?
      -# perhaps if may_select_access_participations is false, then a default should be hard coded? -elijah
      -#
      -# I thought may_select_access_participation? might become a per user setting.
      -# In that case the access value can differ even if this person can not change it.
      -# However you are right about hardcoding it. It should be hardcoded to not change.
      -# Currently we only use it as a per site setting - so it could even be completely
      -# hard coded. -azul
      = hidden_field "recipients[#{recipient.name}]", :access, value: access
  %td
    - if newitem
      = link_to_function_icon('tiny_trash', remove_function, title: I18n.t(:remove))

app/views/page/shares/_share_form.html.haml
- notify = true if notify.nil?
= page_popup_form('share') do
  .tab_area
    .share_page
      .legend= :share_page_recipients.t(page_class: :page.t)
      = render 'add_recipient_widget'
      - if notify
        %br
        .legend= :notification.t
        = render 'notification_message_form'
  .buttons-right
    = spinner 'popup'
    = close_modal_button
    = submit_tag :share.t, name: 'share_button', class: 'btn btn-primary'

app/views/page/shares/show_notify.html.haml
= render 'notify_form'

app/views/page/shares/show_share.html.haml
= formy(:tabs, class: 'flat') do |f|
  - f.tab do |t|
    - t.label :share.t
    - t.show_tab 'share_tab'
    - t.selected true
  - f.tab do |t|
    - t.label :permissions.t
    - t.show_tab 'permissions_tab'
    - t.selected false

#share_tab.tab_content
  = render 'share_form'

#permissions_tab.tab_content{style:'display:none'}
  .tab_area
    = render 'page/participations/permissions'
  .buttons-right
    = close_modal_button